namespace rer
{
    internal enum EnemyType : byte
    {
        ZombieCop = 0x10,
        ZombieBrad,
        ZombieGuy1,
        ZombieGirl,
        ZombieTestSubject = 0x15,
        ZombieScientist,
        ZombieNaked,
        ZombieGuy2,
        ZombieGuy3 = 0x1E,
        ZombieRandom,
        Cerebrus,
        Crow,
        LickerRed,
        Alligator,
        LickerGrey,
        Spider,
        BabySpider,
        Cockroach = 0x29,
        Tyrant1,
        Tyrant2,
        ZombieArms = 0x2D,
        Ivy = 0x2E,
        IvyPurple = 0x39,
        GiantMoth = 0x3A,
        Maggots = 0x3B,
        ChiefIrons1 = 0x40,
        AdaWong1,
        ChiefIrons2,
        AdaWong2,
        BenBertolucci1,
        SherryWithPendant,
        BenBertolucci2,
        AnnetteBirkin1,
        RobertKendo,
        AnnetteBirkin2,
        MarvinBranagh,
        MayorsDaughter,
        SherryWithClairesJacket = 0x4F,
        LeonKennedyRpd,
        ClaireRedfield,
        LeonKennedyBandaged = 0x54,
        ClaireRedfieldNoJacket,
        LeonKennedyCapTankTop = 0x58,
        ClaireRedfieldCowGirl,
        LeonKennedyBlackLeather,
    }
}
