namespace rer
{
    internal class Items
    {
        public static string GetItemName(int id) => id < 0 || id >= _items.Length ? "?" : _items[id];

        private static string[] _items = new string[]
        {
            "nothing",
            "Knife",
            "HK VP70",
            "Browning",
            "Custom Handgun",
            "Magnum",
            "Custom Magnum",
            "Shogun",
            "Custom Shotgun",
            "Grenade Launcher",
            "Grenade Launcher fire",
            "Grenade Launcher Acid",
            "Bowgun",
            "Colt S.A.A",
            "Sparkshot",
            "Ingram",
            "Flamethrower",
            "Rocket Launcher",
            "Gatling Gun",
            "Beretta M29FS",
            "Handgun Ammo",
            "Shotgun Ammo",
            "Magnum Ammo",
            "Flamer Fuel",
            "Grenade Rounds",
            "Flame Rounds",
            "Acid Rounds",
            "SMG ammo",
            "Sparkshot ammo",
            "Bowgun Ammo",
            "Ink Ribbon",
            "Small Key",
            "Handgun Parts",
            "Magnum Parts",
            "Shotgun Parts",
            "F-Aid Spray",
            "Antivirus Bomb",
            "Chemical ACw-32",
            "Green Herb",
            "Red Herb",
            "Blue Herb",
            "G + G Herb",
            "G + R Herb",
            "G + B Herb",
            "G + G + G Herb",
            "G + G + B Herb",
            "G + R + B Herb",
            "Lighter",
            "Lockpick",
            "Sherry Photo",
            "Valve Handle",
            "Red Jewel",
            "Red Card",
            "Blue Card",
            "Serpent Stone",
            "Jaguar Stone",
            "Jaguar Stone L",
            "Jaguar Stone R",
            "Eagle Stone",
            "Bishop Plug",
            "Rook Plug",
            "Knight Plug",
            "King Plug",
            "Weapon Storage key",
            "Detonator",
            "C4",
            "C4+ Detonator",
            "Crank",
            "Film A",
            "Film B",
            "Film C",
            "Unicorn Medal",
            "Eagle Medal",
            "Wolf Medal",
            "Cog",
            "Manhole opener",
            "Main Fuse",
            "Fuse Case",
            "Vaccine",
            "Vaccine Container",
            "Film D",
            "Base Vaccine",
            "G-Virus",
            "Special Key",
            "Joint S Plug",
            "Joint N Plug",
            "Wire",
            "Ada's Photo",
            "Cabin Key",
            "Spade Key",
            "Diamond Key",
            "Heart Key",
            "Club Key",
            "Control Pannel Key (Down)",
            "Control Pannel Key (Up)",
            "Power Room Key",
            "MO Disk",
            "Umbrella KeyCard",
            "Master Key",
            "Platform Key",
        };
    }
}
