namespace rer
{
    internal enum Opcode : byte
    {

        Nop,
        EvtEnd,
        EvtNext,
        EvtChain,
        EvtExec,
        EvtKill,
        IfelCk,
        ElseCk,
        EndIf,
        Sleep,
        Sleeping,
        Wsleep,
        Wsleeping,
        For,
        Next,
        While,
        Ewhile,
        Do,
        Edwhile,
        Gosub = 0x18,
        WorkCopy = 0x1D,
        Ck = 0x21,
        Set,
        Cmp,
        Save,
        Copy,
        Calc,
        Calc2,
        SceRnd,
        CutChg,
        MessageOn = 0x2B,
        AotSet = 0x2C,
        ObjModelSet,
        WorkSet,
        SpeedSet,
        AddSpeed,
        AddASpeed,
        PosSet,
        DirSet,
        MemberSet,
        MemberSet2,
        SeOn,
        DoorAotSe = 0x3B,
        CutAuto,
        MemberCopy,
        MemberCmp,
        PlcDest = 0x40,
        PlcNeck = 0x41,
        PlcRet = 0x42,
        AotReset = 0x46,
        AotOn = 0x47,
        ItemAotSet = 0x4E,
        SceBgmControl = 0x51,
        SceEspr3dOn = 0x54,
        SceBgmtblSet = 0x57,
        SceItemLost = 0x62,
        PlcStop = 0x66,
        DoorAotSet4p = 0x68,
        SceScrMove = 0x6D,
        MovieOn = 0x6F,
        Unk81 = 0x81
    }
}
