namespace IntelOrca.Biohazard
{
    internal enum EnemyType : byte
    {
        ZombieCop = 16,
        ZombieBrad,
        ZombieGuy1,
        ZombieGirl,
        ZombieTestSubject = 21,
        ZombieScientist,
        ZombieNaked,
        ZombieGuy2,
        ZombieGuy3 = 30,
        ZombieRandom,
        Cerebrus,
        Crow,
        LickerRed,
        Alligator,
        LickerGrey,
        Spider,
        BabySpider,
        BirkinGoo,
        BirkinGooChild,
        Cockroach = 41,
        Tyrant1,
        Tyrant2,
        ZombieArms = 45,
        Ivy = 46,
        Vines = 47,
        Birkin1,
        Birkin2,
        Birkin3,
        Birkin4,
        Birkin5,
        IvyPurple = 57,
        GiantMoth = 58,
        Maggots,
        ChiefIrons1 = 64,
        AdaWong1,
        ChiefIrons2,
        AdaWong2,
        BenBertolucci1,
        SherryWithPendant,
        BenBertolucci2,
        AnnetteBirkin1,
        RobertKendo,
        AnnetteBirkin2,
        MarvinBranagh,
        MayorsDaughter,
        SherryWithClairesJacket = 79,
        LeonKennedyRpd,
        ClaireRedfield,
        LeonKennedyBandaged = 84,
        ClaireRedfieldNoJacket,
        LeonKennedyCapTankTop = 88,
        ClaireRedfieldCowGirl,
        LeonKennedyBlackLeather,
    }
}
