//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntelOrca.Biohazard {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IntelOrca.Biohazard.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] bgm_clown {
            get {
                object obj = ResourceManager.GetObject("bgm_clown", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] bgm_code {
            get {
                object obj = ResourceManager.GetObject("bgm_code", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] bgm_re0 {
            get {
                object obj = ResourceManager.GetObject("bgm_re0", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] bgm_re1 {
            get {
                object obj = ResourceManager.GetObject("bgm_re1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] bgm_re3 {
            get {
                object obj = ResourceManager.GetObject("bgm_re3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] bgm_re4_creepy_0 {
            get {
                object obj = ResourceManager.GetObject("bgm_re4_creepy_0", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] bgm_re4_creepy_1 {
            get {
                object obj = ResourceManager.GetObject("bgm_re4_creepy_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] bgm_re4_creepy_2 {
            get {
                object obj = ResourceManager.GetObject("bgm_re4_creepy_2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] bgm_re4_creepy_3 {
            get {
                object obj = ResourceManager.GetObject("bgm_re4_creepy_3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] bgm_re4_danger_0 {
            get {
                object obj = ResourceManager.GetObject("bgm_re4_danger_0", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] bgm_re4_danger_1 {
            get {
                object obj = ResourceManager.GetObject("bgm_re4_danger_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] bgm_re4_danger_2 {
            get {
                object obj = ResourceManager.GetObject("bgm_re4_danger_2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] bgm_re4_results {
            get {
                object obj = ResourceManager.GetObject("bgm_re4_results", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] bgm_re4a {
            get {
                object obj = ResourceManager.GetObject("bgm_re4a", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] bgm_re4b {
            get {
                object obj = ResourceManager.GetObject("bgm_re4b", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;outside&quot;: [],
        ///  &quot;creepy&quot;: [
        ///    &quot;BGM_00&quot;,
        ///    &quot;BGM_0A&quot;,
        ///    &quot;BGM_0E&quot;,
        ///    &quot;BGM_1A&quot;,
        ///    &quot;BGM_1B&quot;,
        ///    &quot;BGM_1C&quot;,
        ///    &quot;BGM_1D&quot;,
        ///    &quot;BGM_1E&quot;,
        ///    &quot;BGM_02&quot;,
        ///    &quot;BGM_2D&quot;,
        ///    &quot;BGM_2E&quot;,
        ///    &quot;BGM_3A&quot;,
        ///    &quot;BGM_3E&quot;,
        ///    &quot;BGM_07&quot;,
        ///    &quot;BGM_09&quot;,
        ///    &quot;BGM_14&quot;,
        ///    &quot;BGM_15&quot;,
        ///    &quot;BGM_16&quot;,
        ///    &quot;BGM_17&quot;,
        ///    &quot;BGM_18&quot;,
        ///    &quot;BGM_19&quot;,
        ///    &quot;BGM_20&quot;,
        ///    &quot;BGM_26&quot;,
        ///    &quot;BGM_30&quot;,
        ///    &quot;BGM_32&quot;,
        ///    &quot;BGM_33&quot;,
        ///    &quot;BGM_34&quot;,
        ///    &quot;BGM_36&quot;,
        ///    &quot;BGM_37&quot;,
        ///    &quot;BGM_40&quot;,
        ///    &quot;BGM_49&quot;
        ///  ],
        ///  &quot;calm&quot;: [
        ///    &quot;BGM_0C&quot;,
        ///    &quot;BGM_3F&quot;,
        ///  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string re1_bgm {
            get {
                return ResourceManager.GetString("re1_bgm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;beginEndRooms&quot;: [
        ///    {
        ///      &quot;start&quot;: &quot;106&quot;,
        ///      &quot;end&quot;: &quot;501&quot;
        ///    }
        ///  ],
        ///  &quot;rooms&quot;: {
        ///    &quot;100&quot;: {
        ///      &quot;linkedRoom&quot;: &quot;600&quot;,
        ///      &quot;doorRando&quot;: [
        ///        {
        ///          &quot;category&quot;: &quot;box&quot;
        ///        }
        ///      ],
        ///      &quot;doors&quot;: [
        ///        {
        ///          &quot;target&quot;: &quot;101&quot;
        ///        }
        ///      ],
        ///      &quot;items&quot;: [
        ///        {
        ///          &quot;id&quot;: 3,
        ///          &quot;type&quot;: 0,
        ///          &quot;player&quot;: 1
        ///        },
        ///        {
        ///          &quot;id&quot;: 4,
        ///          &quot;type&quot;: 0,
        ///          &quot;player&quot;: 1
        ///        },
        ///        {
        ///          &quot;id&quot;: 6,
        ///          &quot;type&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string re1_rdt {
            get {
                return ResourceManager.GetString("re1_rdt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;voice/V001_00.wav&quot;: { &quot;rdt&quot;: &quot;106&quot;, &quot;player&quot;: 0, &quot;actor&quot;: &quot;jill&quot; },
        ///  &quot;voice/V001_01.wav&quot;: {
        ///    &quot;rdt&quot;: &quot;106&quot;,
        ///    &quot;player&quot;: 0,
        ///    &quot;actors&quot;: [
        ///      {
        ///        &quot;actor&quot;: &quot;chris&quot;,
        ///        &quot;split&quot;: 2.5
        ///      },
        ///      {
        ///        &quot;actor&quot;: &quot;wesker&quot;
        ///      }
        ///    ]
        ///  },
        ///  &quot;voice/V001_02.wav&quot;: { &quot;rdt&quot;: &quot;106&quot;, &quot;player&quot;: 0, &quot;actor&quot;: &quot;jill&quot; },
        ///  &quot;voice/V001_03.wav&quot;: {
        ///    &quot;rdt&quot;: &quot;106&quot;,
        ///    &quot;player&quot;: 0,
        ///    &quot;actors&quot;: [
        ///      {
        ///        &quot;actor&quot;: &quot;jill&quot;,
        ///        &quot;split&quot;: 1
        ///      },
        ///      {
        ///        &quot;actor&quot;: &quot;chris&quot;,
        ///     [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string re1_voice {
            get {
                return ResourceManager.GetString("re1_voice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;basement&quot;: [
        ///    &quot;main03&quot;
        ///  ],
        ///  &quot;safe&quot;: [
        ///    &quot;main0C&quot;
        ///  ],
        ///  &quot;results&quot;: [
        ///    &quot;main2a&quot;
        ///  ],
        ///  &quot;outside&quot;: [
        ///    &quot;main00&quot;,
        ///    &quot;main00_2&quot;,
        ///    &quot;main2d&quot;,
        ///    &quot;main2e&quot;,
        ///    &quot;main2f&quot;
        ///  ],
        ///  &quot;creepy&quot;: [
        ///    &quot;main01&quot;,
        ///    &quot;main02&quot;,
        ///    &quot;main03&quot;,
        ///    &quot;main05&quot;,
        ///    &quot;main06&quot;,
        ///    &quot;main07&quot;,
        ///    &quot;main08&quot;,
        ///    &quot;main0e&quot;,
        ///    &quot;main13&quot;,
        ///    &quot;main17&quot;,
        ///    &quot;main18&quot;,
        ///    &quot;main1f&quot;,
        ///    &quot;main22&quot;,
        ///    &quot;main24&quot;,
        ///    &quot;main25&quot;,
        ///    &quot;main27&quot;,
        ///    &quot;main29&quot;,
        ///    &quot;main2b&quot;,
        ///    &quot;main2c&quot;,
        ///    &quot;main30&quot;,
        ///    &quot;main31&quot;,
        ///    &quot;sub01&quot;,
        ///  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string re2_bgm {
            get {
                return ResourceManager.GetString("re2_bgm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///  {
        ///    &quot;100&quot;: 11540303924482159729,
        ///    &quot;101&quot;: 13484268733146939713,
        ///    &quot;102&quot;: 5121006935139844277,
        ///    &quot;103&quot;: 10341030386208010764,
        ///    &quot;104&quot;: 11191520104056313003,
        ///    &quot;105&quot;: 5215203298627972236,
        ///    &quot;106&quot;: 16585113434961875648,
        ///    &quot;107&quot;: 17825891442521666128,
        ///    &quot;108&quot;: 3097568301807621346,
        ///    &quot;109&quot;: 10000667466794830110,
        ///    &quot;10A&quot;: 3484893664893460510,
        ///    &quot;10B&quot;: 17768578808045182216,
        ///    &quot;10C&quot;: 6179190804579467222,
        ///    &quot;10D&quot;: 9902988025485380595,
        ///    &quot;10E&quot;: 2723650462499140465,
        ///    &quot;10F&quot;: 1859652 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string re2_checksum {
            get {
                return ResourceManager.GetString("re2_checksum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;beginEndRooms&quot;: [
        ///    {
        ///      &quot;start&quot;: &quot;100&quot;,
        ///      &quot;end&quot;: &quot;617&quot;,
        ///      &quot;scenario&quot;: 0
        ///    },
        ///    {
        ///      &quot;start&quot;: &quot;104&quot;,
        ///      &quot;end&quot;: &quot;702&quot;,
        ///      &quot;scenario&quot;: 1,
        ///      &quot;doorRando&quot;: false
        ///    },
        ///    {
        ///      &quot;start&quot;: &quot;104&quot;,
        ///      &quot;end&quot;: &quot;700&quot;,
        ///      &quot;scenario&quot;: 1,
        ///      &quot;doorRando&quot;: true
        ///    }
        ///  ],
        ///  &quot;rooms&quot;: {
        ///    &quot;100&quot;: {
        ///      &quot;doors&quot;: [
        ///        {
        ///          &quot;target&quot;: &quot;101&quot;,
        ///          &quot;noReturn&quot;: true
        ///        }
        ///      ],
        ///      &quot;enemies&quot;: [
        ///        {
        ///          &quot;nop&quot;: [ 4888 ]
        ///        }
        ///      ]
        ///    },
        ///    [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string re2_rdt {
            get {
                return ResourceManager.GetString("re2_rdt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;pl0/voice/stage0/v001.sap&quot;: { &quot;player&quot;: 0, &quot;actor&quot;: &quot;narrator&quot; },
        ///    &quot;pl0/voice/stage0/v002.sap&quot;: { &quot;player&quot;: 0, &quot;actor&quot;: &quot;narrator&quot; },
        ///    &quot;pl0/voice/stage0/v003.sap&quot;: { &quot;player&quot;: 0, &quot;actor&quot;: &quot;narrator&quot; },
        ///    &quot;pl0/voice/stage0/v004.sap&quot;: { &quot;player&quot;: 0, &quot;actor&quot;: &quot;narrator&quot; },
        ///    &quot;pl0/voice/stage0/v005.sap&quot;: { &quot;player&quot;: 0, &quot;actor&quot;: &quot;narrator&quot; },
        ///    &quot;pl0/voice/stage0/v006.sap&quot;: { &quot;player&quot;: 0, &quot;actor&quot;: &quot;narrator&quot; },
        ///    &quot;pl0/voice/stage0/v007.sap&quot;: { &quot;player&quot;: 0, &quot;actor&quot;: &quot;narrator&quot; },
        ///    &quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string re2_voice {
            get {
                return ResourceManager.GetString("re2_voice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;pl0/voice/stage0/v001.sap&quot;: { &quot;player&quot;: 0, &quot;actor&quot;: &quot;narrator&quot; },
        ///    &quot;pl0/voice/stage0/v002.sap&quot;: { &quot;player&quot;: 0, &quot;actor&quot;: &quot;narrator&quot; },
        ///    &quot;pl0/voice/stage0/v003.sap&quot;: { &quot;player&quot;: 0, &quot;actor&quot;: &quot;narrator&quot; },
        ///    &quot;pl0/voice/stage0/v004.sap&quot;: { &quot;player&quot;: 0, &quot;actor&quot;: &quot;narrator&quot; },
        ///    &quot;pl0/voice/stage0/v005.sap&quot;: { &quot;player&quot;: 0, &quot;actor&quot;: &quot;narrator&quot; },
        ///    &quot;pl0/voice/stage0/v006.sap&quot;: { &quot;player&quot;: 0, &quot;actor&quot;: &quot;narrator&quot; },
        ///    &quot;pl0/voice/stage0/v007.sap&quot;: { &quot;player&quot;: 0, &quot;actor&quot;: &quot;narrator&quot; },
        ///    &quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string re2_voice1 {
            get {
                return ResourceManager.GetString("re2_voice1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] title_bg_1 {
            get {
                object obj = ResourceManager.GetObject("title_bg_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] title_bg_2 {
            get {
                object obj = ResourceManager.GetObject("title_bg_2", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
