name: CI
on: [push, pull_request]
jobs:
  build:
    name: Build biorand
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: true
    - name: Restore
      run: dotnet restore
    - name: Build
      shell: cmd
      run: |
        call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\Tools\VsDevCmd.bat"
        msbuild biorand.sln /t:build /p:Configuration=Release
    - name: Publish
      working-directory: biorand
      shell: cmd
      run: |
        dotnet publish -c Release --no-build
        cd bin\Release\net472\publish
        copy ${{ github.workspace }}\README.md .
        copy ${{ github.workspace }}\CHANGELOG.md .
        copy ${{ github.workspace }}\LICENSE .
        md ${{ github.workspace }}\artefacts
        del *.pdb
        7z -r a ${{ github.workspace }}\artefacts\biorand.zip data *.exe *.dll *.config README.md CHANGELOG.md LICENSE

        rd /s /q data\bgm data\voice data\hurt data\title
        rd /s /q data\re1\emd data\re1\pld0 data\re1\pld1
        rd /s /q data\re2\emd data\re2\pld0 data\re2\pld1 data\re2\credits
        rd /s /q data\re3\emd data\re3\pld0
        7z -r a ${{ github.workspace }}\artefacts\biorand_slim.zip data *.exe *.dll *.config README.md CHANGELOG.md LICENSE
    - name: Upload artifact (slim)
      uses: actions/upload-artifact@v4
      with:
        name: biorand-slim
        compression-level: 0
        path: artefacts/biorand_slim.zip
    - name: Upload artifact (full)
      uses: actions/upload-artifact@v4
      with:
        name: biorand
        compression-level: 0
        path: artefacts/biorand.zip
    - name: Create release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/v')
      with:
        fail_on_unmatched_files: true
        files: |
          artefacts/biorand.zip
