name: CI
on: [push, pull_request]
jobs:
  build:
    name: Build biorand
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: true
    - name: Restore
      run: dotnet restore
    - name: Build
      shell: cmd
      run: |
        call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\Tools\VsDevCmd.bat"
        msbuild biorand.sln /t:build /p:Configuration=Release
    - name: Publish
      working-directory: biorand
      shell: cmd
      run: |
        dotnet publish -c Release --no-build
        cd bin/Release/net472/publish
        copy ${{ github.workspace }}/README.md .
        copy ${{ github.workspace }}/CHANGELOG.md .
        copy ${{ github.workspace }}/LICENSE .
        md ${{ github.workspace }}/artefacts
        del *.pdb
        7z -r a ${{ github.workspace }}/artefacts/biorand.zip data *.exe *.dll *.config README.md CHANGELOG.md LICENSE
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: biorand
        path: biorand/bin/Release/net472/publish/**/*
    - name: Create release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/v')
      with:
        fail_on_unmatched_files: true
        files: |
          artefacts/biorand.zip
